sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Mkf88JTHSaYXpCTwWdbNHQU3KGJJ3FO97YxjHqNGTfRJfvfN/dbZf/OdCRwAH7iBRHKSPNzJbvYD7Vk1LdMmJ/YKiAkP4Xms7VvITt73yiLwKuiXvIDlu2/7YhqmSvcD40FE2HIw0FtwD7YBGhdlP/MImkN9CNLvF2rDtq7YImGAs5cDeN424ABMS6isoomdTyR4QW+eXPUhvOUxAhgRIFWv/pjeRVQBeu/kQ1BfRuXyXDDDTY+KCGOkd2Px551CsJUgYr6Mr3KRxs5TpJxl5myQP/MyatcoCBHGx8/RuHdA39WQ7GQj3ezwwz54BrFs12stnG62KcNJEA2U0D6VIbECexnbyo/Gi+sydae1Rb15MvaGV/pfWJQh6rHYNtd6bXZRYSIAeiOt0pfpwK8Bs8KDmbRXcvgNqImPhBXeOaY7JTxbiYNadDSOUwhp6xjQYXNrLFPD7r8SorDC4tbNXHXoOaS+CvBuxPENQfdfpp3+wT6qgF32ovynnzCOhkWOzIbzjghbIDE7oR85cWiHCnRoQWvUdqJHqfZ6rFWrOHj9G4iWUuHeBQoD7A6OWnLcy3xR4lkq2NJYLSyYVkQA78TldrYWQhsXOpXBbyvZzA29+yZmIQBTyZmP1HzzRMCtg10lCemJ96c0XGyECyOXUOJesqB+mOhq69QIMB9/1Gk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Andersonville--A-Story-of-Rebel-Military-Prisons---Volume-2_4258
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy